version: '3'
services:
  db_mysql:
    image: mysql:8.0.33
    platform: linux/arm64/v8
    ports:
      - '3306:3306'
    restart: always
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: 'redis:7-alpine'
    platform: linux/arm64/v8
    ports:
      - '6379:6379'
    command: ['redis-server', '--bind', 'redis', '--port', '6379']

  app:
    depends_on:
      - redis
      - db_mysql
    build:
      context: .
      args:
        ENVIRONMENT_NAME: .docker
        BUILD_NAME: docker
    restart: always
    ports:
      - 9000:9000
    env_file:
      - .env.docker
